[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options= "nosniff"
    Referrer-Policy=" no-referrer"
    
# cache for 36days
	  cache-control = '''
    max-age=3153600, 
    public,
    must-revalidate'''
    
    content-security-policy='''
    script-src 'self'; 
    require-trusted-types-for 'script';
    connect-src 'self';
    base-uri 'self';
    object-src 'none';
    frame-ancestors 'none';
    img-src https:;
    '''
    