[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options= "nosniff"
    Referrer-Policy=" no-referrer"
    
    content-security-policy='''
    script-src 'self'; 
    require-trusted-types-for 'script';
    connect-src 'self' https://v1.nocodeapi.com/panugr/google_sheets/weAjdfuhKgnxoMqy?tabId=Projects&row_id=2;
    base-uri 'self';
    object-src 'none';
    frame-ancestors 'none';
    img-src https:;
    '''
    
