[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options= "nosniff"
    Referrer-Policy=" no-referrer, strict-origin-when-cross-origin"

	  cache-control = '''
    max-age=3153600, 
    public,
    must-revalidate'''
    
    content-security-policy='''
    default-src https:;
    connect-src 'self'; 
    base-uri 'self';
    object-src 'none';
    frame-ancestors 'none';
    style-src 'self';
     img-src https:;
    '''
# script-src 'self';
    