[[headers]]
  for = "src/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options= "nosniff"
    Referrer-Policy=" no-referrer"
    
    content-security-policy='''
    script-src 'self'; 
    connect-src 'self' https://v1.nocodeapi.com/panugr/google_sheets/weAjdfuhKgnxoMqy;
    base-uri 'self';
    object-src 'none';
    frame-ancestors 'none';
    img-src https:;
    '''
    
[[plugins]]
  package = "netlify-plugin-html-validate"
  package = "netlify-plugin-checklinks"
  package = "@netlify/plugin-a11y"