[build]
  base= './'
  publish = './'


[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options= "nosniff"
    Referrer-Policy=" no-referrer, strict-origin-when-cross-origin"
    Strict-Transport-Security= "max-age=31536000; includeSubDomains; preload"
	cache-control = '''
	max-age=31536000,
	must-revalidate'''
    content-security-policy='''
    script-src 'self' 'strict-dynamic', 
    connect-src 'self', 
    img-src 'self', 
    style-src 'self',
    base-uri 'self',
    form-action 'self'    
    '''